imports:
  - { resource: config.yml }

framework:
  router:
    resource: "%kernel.root_dir%/config/routing_dev.yml"
    strict_requirements: true
  profiler: { only_exceptions: false }

web_profiler:
  toolbar: true
  intercept_redirects: false

monolog:
  handlers:
    main:
      type:   stream
      path:   "%kernel.logs_dir%/%kernel.environment%.log"
      level:  debug
    console:
      type:   console
      bubble: false
      verbosity_levels:
        VERBOSITY_VERBOSE: INFO
        VERBOSITY_VERY_VERBOSE: DEBUG
      channels: ["!doctrine"]
    console_very_verbose:
      type:   console
      bubble: false
      verbosity_levels:
        VERBOSITY_VERBOSE: NOTICE
        VERBOSITY_VERY_VERBOSE: NOTICE
        VERBOSITY_DEBUG: DEBUG
      channels: ["doctrine"]
  # uncomment to get logging in your browser
  # you may have to allow bigger header sizes in your Web server configuration
  #firephp:
  #    type:   firephp
  #    level:  info
  #chromephp:
  #    type:   chromephp
  #    level:  info

assetic:
  use_controller: true

#swiftmailer:
#  delivery_address: me@example.com

services:
  librarian.storage.events.book:
    alias: librarian.storage.events.book.memory
  librarian.storage.documents.book:
    alias: librarian.storage.documents.book.memory

  librarian.storage.events.user:
    alias: librarian.storage.events.user.mongodb
  librarian.storage.documents.user:
    alias: librarian.storage.documents.user.elasticsearch

  librarian.commandhandler.add_book:
    alias: librarian.commandhandler.add_book.logging
  librarian.commandhandler.add_author:
    alias: librarian.commandhandler.add_author.logging
  librarian.commandhandler.checkout_book:
    alias: librarian.commandhandler.checkout_book.logging
  librarian.commandhandler.return_book:
    alias: librarian.commandhandler.return_book.logging

  librarian.commandhandler.create_user:
    alias: librarian.commandhandler.create_user.logging

  librarian.eventhandler.book_added:
    alias: librarian.eventhandler.book_added.logging
  librarian.eventhandler.author_added:
    alias: librarian.eventhandler.author_added.logging
  librarian.eventhandler.book_checkedout:
    alias: librarian.eventhandler.book_checkedout.logging
  librarian.eventhandler.book_returned:
    alias: librarian.eventhandler.book_returned.logging

  librarian.eventhandler.user_created:
    alias: librarian.eventhandler.user_created.logging

parameters:
  librarian.database.events.host: 172.17.42.1
  librarian.database.events.port: 27017
  librarian.database.documents.host: 172.17.42.1
  librarian.database.documents.port: 9200
