home:
  path: /
  defaults: { _controller: AppBundle:Default:app }
  methods: [ GET ]

app:
  path: /{page}
  defaults: { _controller: AppBundle:Default:app }
  methods: [ GET ]

api_books:
  resource: "@AppBundle/Controller/"
  type:     annotation
  prefix:   /api

