services:
  librarian.eventstore:
    class: AppBundle\EventStore\EventStore
    calls:
      - [setLogger, ["@logger"]]

  librarian.repository.books:
    class: AppBundle\Domain\Repository\Books
    arguments: ["@librarian.eventstore"]

  librarian.commandhandler.register_book:
    class: AppBundle\Domain\CommandHandler\RegisterBookHandler
    arguments: ["@librarian.repository.books"]
    calls:
      - [setLogger, ["@logger"]]

  librarian.commandbus:
    class: AppBundle\Service\CommandBus
    arguments: [{AppBundle\Domain\Command\RegisterBook: "@librarian.commandhandler.register_book"}]
