services:
  # aggregate read model
  librarian.readmodel.book:
    class: AppBundle\Domain\ReadModel\Book

  # event storage
  librarian.storage.events.memory:
    class: AppBundle\EventStore\Storage\MemoryStorage

  # event store
  librarian.eventstore:
    class: AppBundle\EventStore\EventStore
    arguments: ["@librarian.eventbus", "@librarian.storage.events.memory"]

  # aggregate repositories
  librarian.repository.books:
    class: AppBundle\Domain\Repository\Books
    arguments: ["@librarian.eventstore"]

  # message buses
  librarian.commandbus:
    class: AppBundle\MessageBus\CommandBus
    arguments: [{ AppBundle\Domain\Message\Command\AddBook: "@librarian.commandhandler.add_book.logging", AppBundle\Domain\Message\Command\AddAuthor: "@librarian.commandhandler.add_author.logging" }]

  librarian.eventbus:
    class: AppBundle\MessageBus\EventBus
    arguments: [{ AppBundle\Domain\Message\Event\BookAdded: ["@librarian.eventhandler.logging"], AppBundle\Domain\Message\Event\AuthorAdded: ["@librarian.eventhandler.logging"] }]

  # command/event handlers
  librarian.eventhandler.logging:
    class: AppBundle\Domain\MessageHandler\EventHandler\LoggingDecorator
    arguments: ["@logger", "@librarian.readmodel.book"]
  
  librarian.commandhandler.add_book:
    class: AppBundle\Domain\MessageHandler\CommandHandler\AddBookHandler
    arguments: ["@librarian.repository.books"]

  librarian.commandhandler.add_book.logging:
    class: AppBundle\Domain\MessageHandler\CommandHandler\LoggingDecorator
    arguments: ["@logger", "@librarian.commandhandler.add_book"]

  librarian.commandhandler.add_author:
    class: AppBundle\Domain\MessageHandler\CommandHandler\AddAuthorHandler
    arguments: ["@librarian.repository.books"]

  librarian.commandhandler.add_author.logging:
    class: AppBundle\Domain\MessageHandler\CommandHandler\LoggingDecorator
    arguments: ["@logger", "@librarian.commandhandler.add_author"]

  # aggregate services
  librarian.service.book:
    class: AppBundle\Domain\Service\BookService
    arguments: ["@librarian.readmodel.book", "@librarian.commandbus"]
