services:
  librarian.readmodel:
    class: AppBundle\Domain\Service\BookReadModel

  librarian.eventhandler.logging:
    class: AppBundle\Domain\MessageHandler\EventHandler\LoggingEventHandler
    arguments: ["@logger", "@librarian.readmodel"]

  librarian.eventbus:
    class: AppBundle\MessageBus\EventBus
    arguments: [{AppBundle\Domain\Message\Event\BookRegistered: ["@librarian.eventhandler.logging"]}]

  librarian.eventstore:
    class: AppBundle\EventStore\EventStore
    arguments: ["@librarian.eventbus"]

  librarian.repository.books:
    class: AppBundle\Domain\Repository\Books
    arguments: ["@librarian.eventstore"]

  librarian.commandhandler.register_book:
    class: AppBundle\Domain\MessageHandler\CommandHandler\RegisterBookHandler
    arguments: ["@librarian.repository.books"]

  librarian.commandhandler.register_book.logging:
    class: AppBundle\Domain\MessageHandler\CommandHandler\LoggingCommandHandler
    arguments: ["@logger", "@librarian.commandhandler.register_book"]

  librarian.commandbus:
    class: AppBundle\MessageBus\CommandBus
    arguments: [{AppBundle\Domain\Message\Command\RegisterBook: "@librarian.commandhandler.register_book.logging"}]

  librarian.service.book:
    class: AppBundle\Domain\Service\BookService
    arguments: ["@librarian.readmodel", "@librarian.commandbus"]

  librarian.service.book.logging:
    class: AppBundle\Domain\MessageHandler\EventHandler\LoggingEventHandler
    arguments: ["@logger", "@librarian.service.book"]
