services:
  librarian.eventbus:
    class: AppBundle\MessageBus\EventBus
    arguments: [{AppBundle\Domain\Message\Event\BookRegistered: ["@librarian.readmodel.service.logging"]}]

  librarian.eventstore:
    class: AppBundle\EventStore\EventStore
    arguments: ["@librarian.eventbus"]

  librarian.repository.books:
    class: AppBundle\Domain\Repository\Books
    arguments: ["@librarian.eventstore"]

  librarian.commandhandler.register_book:
    class: AppBundle\Domain\MessageHandler\CommandHandler\RegisterBookHandler
    arguments: ["@librarian.repository.books"]

  librarian.commandhandler.register_book.logging:
    class: AppBundle\Domain\MessageHandler\CommandHandler\LoggingCommandHandler
    arguments: ["@logger", "@librarian.commandhandler.register_book"]

  librarian.commandbus:
    class: AppBundle\MessageBus\CommandBus
    arguments: [{AppBundle\Domain\Message\Command\RegisterBook: "@librarian.commandhandler.register_book.logging"}]

  librarian.readmodel.service:
    class: AppBundle\Domain\Service\ReadModelService

  librarian.readmodel.service.logging:
    class: AppBundle\Domain\MessageHandler\EventHandler\LoggingEventHandler
    arguments: ["@logger", "@librarian.readmodel.service"]
